source 'http://rubygems.org'

gem 'rails', '3.1.0'

group :production do
  gem 'mysql'
end

group :development do
  gem 'rspec-rails', '2.6.1'
  gem 'sqlite3', '1.3.4'
  gem 'sqlite3-ruby', '1.2.5', :require => 'sqlite3'
end

group :test do
  gem 'rspec-rails', '2.6.1'
  gem 'spork', '0.9.0.rc8'
  gem 'webrat', '0.7.1'
  gem 'sqlite3', '1.3.4'
  gem 'sqlite3-ruby', '1.2.5', :require => 'sqlite3'
end
